config/routes.rb
DomainPlanner::Application.routes.draw do

  get '/sign_in' => 'user_sessions#new', :as => :sign_in
  post '/sign_in' => 'user_sessions#create', :as => :sign_in
  get '/sign_out' => 'user_sessions#destroy', :as => :sign_out

  get '/welcome-back' => 'welcome#welcome_back', :as => :user_landing

  scope 'about' do
    get 'core_knowledge' => 'about#core_knowledge', :as => :about_core_knowledge
    get 'terms_of_use' => 'about#terms_of_use', :as => :about_terms_of_use
    get 'software' => 'about#software', :as => :about_software
  end

  resources :password_resets, :except => [ :index, :destroy, :show ]

  get '/invitations/:role/new' => 'invitations#new', :as => :new_invitation
  post '/invitations/:role' => 'invitations#create', :as => :invitations
  get '/invitations/accept/:token' => 'invitations#show', :as => :accept_invitation
  put '/invitations/accept/:token' => 'invitations#accept', :as => :accept_invitation

  get '/school_invitations/new' => 'invitations#new_school', :as => :new_school_invitation
  post '/school_invitations' => 'invitations#create_school', :as => :school_invitations

  resources :users, :only => [ :index, :destroy ] do
    member do
      put :activate
      put :deactivate
      put :resend_invitation
    end
  end
  get 'users/all.csv' => 'users#csv'

  get '/me', :to => 'users#edit'
  put '/me', :to => 'users#update'

  get '/my_school/edit' => 'my_school#edit', :as => :edit_my_school
  put '/my_school' => 'my_school#update', :as => :my_school

  scope 'my_school' do
    resources :scheduled_domains
    resources :school_holidays
    resources :school_years, :controller => 'my_school/school_years'

    get 'school_years/:id/transfer' => 'my_school/school_years#transfer', :as => :transfer_school_year
    put 'school_years/:id/transfer' => 'my_school/school_years#complete_transfer'

    get 'school_years/:id/schedule' => 'my_school/school_years#schedule', :as => :school_year_schedule
    put 'school_years/:id/schedule' => 'my_school/school_years#update_schedule'

    resources :domains, :controller => 'my_school/domains', :as => :custom_domains, :only => [:create, :destroy, :update]
    resources :standards, :controller => 'my_school/standards', :as => :custom_standards, :only => [ :create, :destroy, :update ]
    resources :guidelines, :controller => 'my_school/guidelines', :as => :custom_guidelines, :only => [ :create, :destroy, :update ]

    scope '/users' do
      get '/', :to => 'my_school/users#index', :as => :my_school_users
      put '/:id/activate', :to => 'my_school/users#activate', :as => :activate_user
      put '/:id/deactivate', :to => 'my_school/users#deactivate', :as => :deactivate_user
      put '/:id/promote', :to => 'my_school/users#promote', :as => :promote_user
      put '/:id/demote', :to => 'my_school/users#demote', :as => :demote_user
    end

    scope '/domain_maps/:domain_id/school_years/:school_year_id' do
      get '/', :to => 'my_school/domain_maps#show', :as => :domain_map
      post '/guidelines/:guideline_id', :to => 'my_school/mapped_guidelines#create', :as => :mapped_guidelines
      delete '/guidelines/:guideline_id', :to => 'my_school/mapped_guidelines#destroy', :as => :mapped_guidelines
      post '/skills_guidelines/:guideline_id', :to => 'my_school/mapped_skills_guidelines#create', :as => :mapped_skills_guidelines
      delete '/skills_guidelines/:guideline_id', :to => 'my_school/mapped_skills_guidelines#destroy', :as => :mapped_skills_guidelines

      put '/included_standards/:id', :to => 'my_school/domain_maps#include_standard', :as => 'include_standard'
      delete '/included_standards/:id', :to => 'my_school/domain_maps#omit_standard', :as => 'omit_standard'
      get '/included_standards', :to => 'my_school/domain_maps#included_standards', :as => 'included_standards'
      put '/included_skills_standards/:id', :to => 'my_school/domain_maps#include_skills_standard', :as => 'include_skills_standard'
      delete '/included_skills_standards/:id', :to => 'my_school/domain_maps#omit_skills_standard', :as => 'omit_skills_standard'
      get '/included_skills_standards', :to => 'my_school/domain_maps#included_skills_standards', :as => 'included_skills_standards'

      put '/toggle_cross_curricular_link/:id', :to => 'my_school/domain_maps#toggle_cross_curricular_link', :as => 'toggle_cross_curricular_link'

      put '/vocabulary', :to => 'my_school/domain_maps#add_vocabulary', :as => 'domain_map_vocabulary'
      delete '/vocabulary/:word', :to => 'my_school/domain_maps#remove_vocabulary', :as => 'domain_map_vocabulary_word'
    end

    get '/teachers/invitations/new', :to => 'my_school/teacher_invitations#new', :as => :new_teacher_invitation
    post '/teachers/invitations', :to => 'my_school/teacher_invitations#create', :as => :teacher_invitations

    get '/planners/invitations/new', :to => 'my_school/planner_invitations#new', :as => :new_my_school_planner_invitation
    post '/planners/invitations', :to => 'my_school/planner_invitations#create', :as => :my_school_planner_invitations


  end

  get '/domains' => 'domains#grades', :as => :domains
  get '/domains/new' => 'domains#new', :as => :new_domain
  post '/domains' => 'domains#create', :as => :domains
  get '/domains/:grade' => 'domains#grade', :as => :domains_grade
  get '/domains/:grade/:id' => 'domains#show', :as => :domain

  scope '/admin' do

    scope '/curriculum' do
      get '/' => 'curriculum#index', :as => :curriculum
      get '/upload' => 'curriculum#new', :as => :upload_curriculum
      post '/' => 'curriculum#upload', :as => :curriculum
      delete '/' => 'curriculum#clear', :as => :clear_curriculum
      get '/curriculum/node/:id' => 'curriculum#node', :as => :curriculum_node

      get 'node/:id/children/new' => 'admin/curriculum_nodes#new', :as => :new_child_curriculum_node
      get 'node/new' => 'admin/curriculum_nodes#new', :as => :new_curriculum_node
      post 'nodes' => 'admin/curriculum_nodes#create', :as => :curriculum_nodes
      get 'node/:curriculum_node_id/guidelines/new' => 'admin/guidelines#new', :as => :new_guideline
      post 'node/:curriculum_node_id/guidelines' => 'admin/guidelines#create', :as => :guidelines

      get '/curriculum/node/:id/edit' => 'curriculum#edit', :as => :edit_curriculum_node
      put '/curriculum/node/:id' => 'curriculum#update', :as => :curriculum_node
      delete '/curriculum/node/:id' => 'curriculum#destroy', :as => :curriculum_node
    end

    scope '/domains' do
      get '/' => 'admin/domains#new', :as => :upload_domains
      post '/' => 'admin/domains#upload', :as => :upload_domains
      delete '/' => 'admin/domains#clear', :as => :clear_domains
      put '/:id' => 'admin/domains#update', :as => :admin_domain
      delete '/:id' => 'admin/domains#destroy', :as => :admin_domain
    end

    resources :guidelines, :only => [ :show, :edit, :update, :destroy], :controller => 'admin/guidelines' do
      resources :knowledge_connections, :only => [ :create, :destroy ], :controller => 'admin/knowledge_connections'
      resources :domain_applications, :only => [ :create, :destroy ], :controller => 'admin/guideline_domain_applications'
      resources :standard_applications, :only => [ :create, :destroy ], :controller => 'admin/guideline_standard_applications'
      resources :sub_guidelines, :only => [ :create ], :controller => 'admin/sub_guidelines'
    end
    resources :sub_guidelines, :only => [ :edit, :update, :destroy ], :controller => 'admin/sub_guidelines'

    resources :standards, :controller => 'admin/standards'

    get '/upload/standards' => 'admin/standards#new_upload', :as => :new_standards_upload
    get '/standards/*ck_code' => 'admin/standards#show', :as => :standard
    post '/upload/standards' => 'admin/standards#upload', :as => :upload_standards
    delete '/standards' => 'admin/standards#clear', :as => :clear_standards

    get 'logins' => 'admin/login_events#index', :as => :login_events
    get 'schools' => 'admin/schools#index', :as => :admin_schools
    get 'lesson_plans' => 'admin/lesson_plans#index', :as => :admin_lesson_plans
  end

  get 'schools' => 'schools#index', :as => :schools

  get '/curriculum/plan/:grade' => 'my_school#plan', :as => :plan_curriculum
  get '/curriculum/plan/:grade/domains' => 'my_school#domains'
  get '/curriculum/plan/:grade/scheduled_domains' => 'my_school#scheduled_domains'

  get '/my_school/curriculum/(:grade)' => 'teachers/domain_maps#curriculum', :as => :show_curriculum
  get '/my_school/curriculum/school_years/:school_year_id/domain_map/:domain_id' => 'teachers/domain_maps#domain_map', :as => :show_domain_map

  get '/my_calendar' => 'teachers/calendar#show', :as => :teacher_calendar
  get '/my_calendar/events' => 'teachers/calendar#events', :as => :teacher_calendar_events
  post '/my_calendar/:school_year_id/:month_fragment' => 'teachers/calendar#persist_month'

  post '/school_years/:school_year_id/scheduled_lesson_plans' => 'teachers/scheduled_lesson_plans#create', :as => :scheduled_lesson_plans

  get '/guidelines/:guideline_id/knowledge_connections' => 'knowledge_connections#index', :as => :knowledge_connections

  scope '/domains/:domain_id' do
    resources :domain_units, :only => [ :create, :update, :destroy ], :controller => 'schools/domain_units' do
      resources :lesson_plans, :controller => 'teachers/lesson_plans' do
        member { put :clone; put :public_notes }
      end
    end
  end

  resources :lesson_plans, :only => [ :show ], :controller => 'teachers/lesson_plans'

  scope '/reports' do

    # Reports

    get '/', :to => 'reports#index', :as => :reports

    [ :grade_domain_report, :subject_domain_report, :ccss_coverage_report, :domain_week_report, :ss_coverage_report, :full_domain_report, :domain_lessons_report, :related_knowledge_report ].each do |report|
      get "#{ report }/new", :to => "reports/#{ report.to_s.pluralize }#new", :as => "new_#{ report }"

app/controllers/my_school/domain_maps_controller.rb
class MySchool::DomainMapsController < ApplicationController

  before_filter :require_planner, :find_school, :load_domain_map, :load_standards

  def show
    @subjects = CurriculumNode.roots.order('position asc').all
    @curriculum_nodes = @subjects.inject({}) { |acc, s| acc[s] = s.subtree_for_grade(@domain.grade_name); acc }
  end

  def toggle_cross_curricular_link
    @link = KnowledgeConnection.find(params[:id])
    @domain_map.toggle_cross_curricular_link!(@link)
    respond_to do |format|
      format.json { render :json => @link }
    end
  end

  def omit_standard
    @standard = Standard.find(params[:id])
    @domain_map.omit_standard!(@standard)
    respond_to do |format|
      format.json { render :json => @standard }
    end
  end

  def include_standard
    @standard = Standard.find(params[:id])
    @domain_map.include_standard!(@standard)
    respond_to do |format|
      format.json { render :json => @standard }
    end
  end

  def included_standards
    @standards = @domain_map.included_standards
    respond_to do |format|
      format.json { render :json => StandardDecorator.decorate(@standards) }
    end
  end

  def omit_skills_standard
    @standard = Standard.find(params[:id])
    @domain_map.omit_skills_standard!(@standard)
    respond_to do |format|
      format.json { render :json => @standard }
    end
  end

  def include_skills_standard
    @standard = Standard.find(params[:id])
    @domain_map.include_skills_standard!(@standard)
    respond_to do |format|
      format.json { render :json => @standard }
    end
  end

  def included_skills_standards
    @standards = @domain_map.included_skills_standards
    respond_to do |format|
      format.json { render :json => StandardDecorator.decorate(@standards) }
    end
  end

  def add_vocabulary
    @domain_map.add_vocabulary!(params[:word])
    respond_to do |format|
      format.json { render :json => @domain_map.vocabulary }
    end
  end

  def remove_vocabulary
    @domain_map.remove_vocabulary!(params[:word])
    respond_to do |format|
      format.json { render :json => @domain_map.vocabulary }
    end
  end

  private

  def school_year
    @school_year ||= if params[:school_year_id]
                       current_user.update_attribute :last_school_year_id, params[:school_year_id]
                       @school.school_years.find(params[:school_year_id])
                     elsif current_user.last_school_year_id
                       @school.school_years.find(current_user.last_school_year_id) rescue @school.school_year
                     else
                       @school.school_year
                     end
  end

  def load_domain_map
    @domain = Domain.find(params[:domain_id])
    @domain_map = @school.domain_maps.where(:domain_id => @domain.id, :school_year_id => school_year.id).first_or_create!
  end

  def load_standards
    @standards_json ||= Rails.cache.fetch("ccss_standards_json", :expires_in => 1.day) do
      StandardDecorator.all.to_json
    end
    @included_standards ||= StandardDecorator.decorate(@domain_map.included_standards)
    @included_skills_standards ||= StandardDecorator.decorate(@domain_map.included_skills_standards)
  end

end

app/controllers/my_school/domains_controller.rb
class MySchool::DomainsController < ApplicationController

  before_filter :require_planner, :find_school

  def destroy
    @domain = @school.custom_domains.find(params[:id])
    if @domain.destroy
      respond_to do |format|
        format.json { render :json => { :success => :ok } }
      end
    end
  end

  def create
    @domain = @school.custom_domains.create(params[:domain])
    respond_to do |format|
      format.html { redirect_to plan_curriculum_path }
      format.json { render :json => SchoolDomainDecorator.decorate(@domain) }
    end
  end

  def update
    @domain = Domain.find(params[:id])
    if @domain.is_custom?
      @domain.update_attributes(params[:domain])
    else
      if params[:included]
        @school.include_domain!(@domain)
      else
        @school.omit_domain!(@domain)
      end
    end
    respond_to do |format|
      format.json { render :json => SchoolDomainDecorator.decorate(@domain) }
    end
  end

end

app/controllers/my_school/guidelines_controller.rb
class MySchool::GuidelinesController < ApplicationController

  before_filter :require_planner, :find_school

  def destroy
    @guideline = @school.custom_guidelines.find(params[:id])
    if @guideline.destroy
      respond_to do |format|
        format.html { redirect_to request.referer }
        format.json { render :json => { :success => :ok } }
      end
    end
  end

  def create
    @guideline = @school.custom_guidelines.create(params[:guideline])
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { render :json => @guideline }
    end
  end

  def update
    @guideline = @school.custom_guidelines.find(params[:id])
    @guideline.update_attributes(params[:guideline])
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { render :json => @guideline }
    end
  end

end

app/controllers/my_school/lesson_plans_controller.rb
class MySchool::LessonPlansController < ApplicationController

  def show
    @lesson_plan = domain_unit.lesson_plans.find(params[:id])
  end

  private

  def school
    @school ||= current_user.school
  end

  def domain_unit
    @domain_unit ||= school.domain_units.where(:domain_map_id => domain_map.id).find(params[:domain_unit_id])
  end

  def domain_map
    @domain = Domain.find(params[:domain_id])
    @domain_map ||= current_user.school.domain_maps.where(:domain_id => @domain.id).first_or_create!
  end

end

app/controllers/my_school/mapped_guidelines_controller.rb
class MySchool::MappedGuidelinesController < ApplicationController

  before_filter :require_planner, :find_school, :find_domain_map

  def create
    @domain_map.add_guideline!(@guideline)
    respond_to do |format|
      format.json { render :json => { :domain_id => @domain.id, :guideline_id => @guideline.id, :name => @guideline.name.html_safe, :id => @guideline.id, :draggable_text => @guideline.abbreviated_text, :custom => @guideline.custom? } }
    end
  end

  def destroy
    @domain_map.remove_guideline!(@guideline)
    respond_to do |format|
      format.json { render :json => { :success => :ok } }
    end
  end

  private

  def find_domain_map
    @domain = Domain.find(params[:domain_id])
    @guideline = Guideline.find(params[:guideline_id])
    @school_year = params[:school_year_id] ? @school.school_years.find(params[:school_year_id]) : @school.school_year
    @domain_map = @school.domain_maps.where(:domain_id => @domain.id, :school_year_id => @school_year.id).first_or_create!
  end

end

app/helpers/my_school/domain_maps_helper.rb
module MySchool::DomainMapsHelper

  def highlight_if_domain_applicable(node, domain)
    "applicable" if node.domain_applications.any? {|a| a.domain_id == domain.id}
  end

  def mapped_if_guideline_mapped(guideline, domain_map)
    "mapped" if domain_map.guideline_ids.include?(guideline.id) || 
      domain_map.skills_guideline_ids.include?(guideline.id)
  end

end

app/helpers/my_school_helper.rb
module MySchoolHelper
end

app/views/my_school/_week_tab.html.haml
%a{:rel => 'popover', :data => { :title => week.micro_form, :content => week.holidays_text.html_safe, :placement => 'bottom', :html => "true" } }
  Week
  = week.index

app/views/my_school/edit.html.haml
.row
  .span5.well
    = form_for @school, :url => my_school_path, :html => { :class => 'horizontal-form' } do |f|
      %fieldset
        %legend
          %strong My School

        .control-group
          = f.label :name, "School Name", :class => 'control-label'
          .controls
            = f.text_field :name, :placeholder => 'e.g. Washington Elementary'


        .control-group
          %p Your Grade Offerings
          .controls.grades
            %table.table.table-bordered
              %tr
                - for grade in School::GRADES
                  %th= label_tag "school[grades][#{ grade }]", grade
              %tr
                - for grade in School::GRADES
                  %td= check_box_tag "school[grades][]", grade, @school.grades.include?(grade)

        .control-group
          .controls= f.submit "Update", :class => 'btn btn-primary'

  .span5.well
    %fieldset
      %legend 
        %a{:rel => "popover", :data => { :title => "School Year", :content => "The term <em>School Year</em> is used to designate any instructional period. The period may be a traditional education year (September to June), or a semester, or a summer session. In the following pages, all of these will be referred to as <em>School Year</em>.".html_safe, :html => "true", :placement => "bottom" } } School Years
      
      %ul
        - for year in @school.school_years
          %li= link_to year.name, edit_school_year_path(year)
        %li= link_to "Add New", new_school_year_path

app/views/my_school/plan.html.haml
.row
  .span2
    %table.table.table-condensed.domain-list
      %tr.grade-header{:class => "grade-#{ @grade }"}
        %th Domains & Topics
      %tr.custom-domain{:class => "grade-#{ @grade }"}
        %td= link_to "Create New...", "#newCustomDomain", :class => 'btn', :data => { :toggle => 'modal', :grade => @grade }

  .span10

    .plan-options{:style => 'float:right; height:100px;'}
      %h4
        %i.icon-print
          = link_to "Print", grade_domain_report_path(:format => 'pdf', :report => { :grade => @grade, :style => 'Table', :school_year_id => @school_year.id })

      = form_tag plan_curriculum_path(:grade => @grade), :method => :get, :id => 'change-school-year' do
        = label_tag 'school_year_id', "School Year"
        = select_tag 'school_year_id', options_for_select(@school.school_years.map {|y| [y.name, y.id]}, @school_year.id)


    %h3
      Curriculum Plan
      = "for #{ @school.name }" if @school.name.present?
      = ": #{ School.grade_name_for(@grade) }"

    %ul.nav.nav-tabs#months
      - for month in @school_year.months
        %li{:id => "month-tab-#{ month.name.downcase }"}= link_to month.name[0..2], "#month-#{ month.name.downcase }", :data => { :month => month.name.downcase, :start_week => month.weeks.first.index, :end_week => month.weeks.last.index, :toggle => 'tab' }, :class => 'show-month'
    .scrollable-calendar
      - for month in @school_year.months
        .calendar-content{:style => "position: relative; min-height: 1px;"}
          .calendar-view{:style => "position: relative;", :unselectable => "on"}
            %table.table.calendar{:class => "month-#{ month.name.downcase }", :data => { :month => month.name.downcase }}

              %tr
                %th Week
                - for week in month.weeks
                  %td.week-title{:id => "week-#{ week.index }"}= render :partial => 'week_tab', :locals => { :week => week }

              - for subject in @subjects
                %tr{:class => "subject-#{ subject.id }"}
                  %th.subject-header{:width => "15%"}= subject.name
                  - for week in month.weeks
                    %td.week-cell{'data-grade' => @grade, 'data-week' => week.index, 'data-subject-id' => subject.id}
            .scheduled-domains{:class => "month-#{ month.name.downcase }", :style => "position: absolute; z-index: 8; top: 0px; left: 0px;"}


%span#grade{:data => { :grade => @grade }}/

= render :partial => 'my_school/domains/new'
= javascript_tag "window.schoolYearId = #{ @school_year.id };"