config/routes.rb
DomainPlanner::Application.routes.draw do

  get '/sign_in' => 'user_sessions#new', :as => :sign_in
  post '/sign_in' => 'user_sessions#create', :as => :sign_in
  get '/sign_out' => 'user_sessions#destroy', :as => :sign_out

  get '/welcome-back' => 'welcome#welcome_back', :as => :user_landing

  scope 'about' do
    get 'core_knowledge' => 'about#core_knowledge', :as => :about_core_knowledge
    get 'terms_of_use' => 'about#terms_of_use', :as => :about_terms_of_use
    get 'software' => 'about#software', :as => :about_software
  end

  resources :password_resets, :except => [ :index, :destroy, :show ]

  get '/invitations/:role/new' => 'invitations#new', :as => :new_invitation
  post '/invitations/:role' => 'invitations#create', :as => :invitations
  get '/invitations/accept/:token' => 'invitations#show', :as => :accept_invitation
  put '/invitations/accept/:token' => 'invitations#accept', :as => :accept_invitation

  get '/school_invitations/new' => 'invitations#new_school', :as => :new_school_invitation
  post '/school_invitations' => 'invitations#create_school', :as => :school_invitations

  resources :users, :only => [ :index, :destroy ] do
    member do
      put :activate
      put :deactivate
      put :resend_invitation
    end
  end
  get 'users/all.csv' => 'users#csv'

  get '/me', :to => 'users#edit'
  put '/me', :to => 'users#update'

  get '/my_school/edit' => 'my_school#edit', :as => :edit_my_school
  put '/my_school' => 'my_school#update', :as => :my_school

  scope 'my_school' do
    resources :scheduled_domains
    resources :school_holidays
    resources :school_years, :controller => 'my_school/school_years'

    get 'school_years/:id/transfer' => 'my_school/school_years#transfer', :as => :transfer_school_year
    put 'school_years/:id/transfer' => 'my_school/school_years#complete_transfer'

    get 'school_years/:id/schedule' => 'my_school/school_years#schedule', :as => :school_year_schedule
    put 'school_years/:id/schedule' => 'my_school/school_years#update_schedule'

    resources :domains, :controller => 'my_school/domains', :as => :custom_domains, :only => [:create, :destroy, :update]
    resources :standards, :controller => 'my_school/standards', :as => :custom_standards, :only => [ :create, :destroy, :update ]
    resources :guidelines, :controller => 'my_school/guidelines', :as => :custom_guidelines, :only => [ :create, :destroy, :update ]

    scope '/users' do
      get '/', :to => 'my_school/users#index', :as => :my_school_users
      put '/:id/activate', :to => 'my_school/users#activate', :as => :activate_user
      put '/:id/deactivate', :to => 'my_school/users#deactivate', :as => :deactivate_user
      put '/:id/promote', :to => 'my_school/users#promote', :as => :promote_user
      put '/:id/demote', :to => 'my_school/users#demote', :as => :demote_user
    end

    scope '/domain_maps/:domain_id/school_years/:school_year_id' do
      get '/', :to => 'my_school/domain_maps#show', :as => :domain_map
      post '/guidelines/:guideline_id', :to => 'my_school/mapped_guidelines#create', :as => :mapped_guidelines
      delete '/guidelines/:guideline_id', :to => 'my_school/mapped_guidelines#destroy', :as => :mapped_guidelines
      post '/skills_guidelines/:guideline_id', :to => 'my_school/mapped_skills_guidelines#create', :as => :mapped_skills_guidelines
      delete '/skills_guidelines/:guideline_id', :to => 'my_school/mapped_skills_guidelines#destroy', :as => :mapped_skills_guidelines

      put '/included_standards/:id', :to => 'my_school/domain_maps#include_standard', :as => 'include_standard'
      delete '/included_standards/:id', :to => 'my_school/domain_maps#omit_standard', :as => 'omit_standard'
      get '/included_standards', :to => 'my_school/domain_maps#included_standards', :as => 'included_standards'
      put '/included_skills_standards/:id', :to => 'my_school/domain_maps#include_skills_standard', :as => 'include_skills_standard'
      delete '/included_skills_standards/:id', :to => 'my_school/domain_maps#omit_skills_standard', :as => 'omit_skills_standard'
      get '/included_skills_standards', :to => 'my_school/domain_maps#included_skills_standards', :as => 'included_skills_standards'

      put '/toggle_cross_curricular_link/:id', :to => 'my_school/domain_maps#toggle_cross_curricular_link', :as => 'toggle_cross_curricular_link'

      put '/vocabulary', :to => 'my_school/domain_maps#add_vocabulary', :as => 'domain_map_vocabulary'
      delete '/vocabulary/:word', :to => 'my_school/domain_maps#remove_vocabulary', :as => 'domain_map_vocabulary_word'
    end

    get '/teachers/invitations/new', :to => 'my_school/teacher_invitations#new', :as => :new_teacher_invitation
    post '/teachers/invitations', :to => 'my_school/teacher_invitations#create', :as => :teacher_invitations

    get '/planners/invitations/new', :to => 'my_school/planner_invitations#new', :as => :new_my_school_planner_invitation
    post '/planners/invitations', :to => 'my_school/planner_invitations#create', :as => :my_school_planner_invitations


  end

  get '/domains' => 'domains#grades', :as => :domains
  get '/domains/new' => 'domains#new', :as => :new_domain
  post '/domains' => 'domains#create', :as => :domains
  get '/domains/:grade' => 'domains#grade', :as => :domains_grade
  get '/domains/:grade/:id' => 'domains#show', :as => :domain

  scope '/admin' do

    scope '/curriculum' do
      get '/' => 'curriculum#index', :as => :curriculum
      get '/upload' => 'curriculum#new', :as => :upload_curriculum
      post '/' => 'curriculum#upload', :as => :curriculum
      delete '/' => 'curriculum#clear', :as => :clear_curriculum
      get '/curriculum/node/:id' => 'curriculum#node', :as => :curriculum_node

      get 'node/:id/children/new' => 'admin/curriculum_nodes#new', :as => :new_child_curriculum_node
      get 'node/new' => 'admin/curriculum_nodes#new', :as => :new_curriculum_node
      post 'nodes' => 'admin/curriculum_nodes#create', :as => :curriculum_nodes
      get 'node/:curriculum_node_id/guidelines/new' => 'admin/guidelines#new', :as => :new_guideline
      post 'node/:curriculum_node_id/guidelines' => 'admin/guidelines#create', :as => :guidelines

      get '/curriculum/node/:id/edit' => 'curriculum#edit', :as => :edit_curriculum_node
      put '/curriculum/node/:id' => 'curriculum#update', :as => :curriculum_node
      delete '/curriculum/node/:id' => 'curriculum#destroy', :as => :curriculum_node
    end

    scope '/domains' do
      get '/' => 'admin/domains#new', :as => :upload_domains
      post '/' => 'admin/domains#upload', :as => :upload_domains
      delete '/' => 'admin/domains#clear', :as => :clear_domains
      put '/:id' => 'admin/domains#update', :as => :admin_domain
      delete '/:id' => 'admin/domains#destroy', :as => :admin_domain
    end

    resources :guidelines, :only => [ :show, :edit, :update, :destroy], :controller => 'admin/guidelines' do
      resources :knowledge_connections, :only => [ :create, :destroy ], :controller => 'admin/knowledge_connections'
      resources :domain_applications, :only => [ :create, :destroy ], :controller => 'admin/guideline_domain_applications'
      resources :standard_applications, :only => [ :create, :destroy ], :controller => 'admin/guideline_standard_applications'
      resources :sub_guidelines, :only => [ :create ], :controller => 'admin/sub_guidelines'
    end
    resources :sub_guidelines, :only => [ :edit, :update, :destroy ], :controller => 'admin/sub_guidelines'

    resources :standards, :controller => 'admin/standards'

    get '/upload/standards' => 'admin/standards#new_upload', :as => :new_standards_upload
    get '/standards/*ck_code' => 'admin/standards#show', :as => :standard
    post '/upload/standards' => 'admin/standards#upload', :as => :upload_standards
    delete '/standards' => 'admin/standards#clear', :as => :clear_standards

    get 'logins' => 'admin/login_events#index', :as => :login_events
    get 'schools' => 'admin/schools#index', :as => :admin_schools
    get 'lesson_plans' => 'admin/lesson_plans#index', :as => :admin_lesson_plans
  end

  get 'schools' => 'schools#index', :as => :schools

  get '/curriculum/plan/:grade' => 'my_school#plan', :as => :plan_curriculum
  get '/curriculum/plan/:grade/domains' => 'my_school#domains'
  get '/curriculum/plan/:grade/scheduled_domains' => 'my_school#scheduled_domains'

  get '/my_school/curriculum/(:grade)' => 'teachers/domain_maps#curriculum', :as => :show_curriculum
  get '/my_school/curriculum/school_years/:school_year_id/domain_map/:domain_id' => 'teachers/domain_maps#domain_map', :as => :show_domain_map

  get '/my_calendar' => 'teachers/calendar#show', :as => :teacher_calendar
  get '/my_calendar/events' => 'teachers/calendar#events', :as => :teacher_calendar_events
  post '/my_calendar/:school_year_id/:month_fragment' => 'teachers/calendar#persist_month'

  post '/school_years/:school_year_id/scheduled_lesson_plans' => 'teachers/scheduled_lesson_plans#create', :as => :scheduled_lesson_plans

  get '/guidelines/:guideline_id/knowledge_connections' => 'knowledge_connections#index', :as => :knowledge_connections

  scope '/domains/:domain_id' do
    resources :domain_units, :only => [ :create, :update, :destroy ], :controller => 'schools/domain_units' do
      resources :lesson_plans, :controller => 'teachers/lesson_plans' do
        member { put :clone; put :public_notes }
      end
    end
  end

  resources :lesson_plans, :only => [ :show ], :controller => 'teachers/lesson_plans'

  scope '/reports' do

    # Reports

    get '/', :to => 'reports#index', :as => :reports

    [ :grade_domain_report, :subject_domain_report, :ccss_coverage_report, :domain_week_report, :ss_coverage_report, :full_domain_report, :domain_lessons_report, :related_knowledge_report ].each do |report|
      get "#{ report }/new", :to => "reports/#{ report.to_s.pluralize }#new", :as => "new_#{ report }"

app/models/standard.rb
class Standard < ActiveRecord::Base

  has_many :standard_applications, :dependent => :destroy
  has_many :guidelines, :through => :standard_applications

  after_save :clear_cache
  after_destroy :clear_cache

  before_create :set_grade

  validates_presence_of :ck_code, :unless => :school_id
  validates_presence_of :subject
  validates_presence_of :text
  validates_presence_of :grade

  acts_as_list :scope => 'origin = #{ origin.present? ? ("\'" + origin + "\'") : "null" }'

  default_scope order('position asc')

  scope :common, -> { where(:school_id => nil) }
  scope :for_grade, lambda { |grade|
    where(:grade => grade)
  }
  scope :for_school, lambda { |school|
    where(:school_id => school.id)
  }
  scope :for_school_or_common, lambda { |school|
    where(:school_id => [nil, school.id])
  }
  scope :for_subject, lambda { |subject|
    where(:subject => subject)
  }

  attr_accessible :grade, :subject, :ck_code, :text, :ck_align, :strand_code, :strand, :category

  def short_text
    short_text = text.size > 40 ? text[0..37] + "..." : text
    short_text.gsub(/<\/?\w+>?/, '')
  end

  def grade_name
    School::GRADE_TRANSLATIONS[grade]
  end

  private

  def clear_cache
    Rails.cache.delete("ccss_standards_json")
  end

  def set_grade
    self.grade = ck_code.split('.').first unless grade.present?
  end

  def self.import(csv)
    csv.each do |row|
      origin = row["Source"] || "CCSS"
      unless row["ckCode"].blank?
        grades = row["ckCode"].split('.').first.split('-')
        if grades.size > 1
          grades = Range.new(*grades.map(&:to_i)).to_a.map &:to_s
        end
        grades.each do |grade|
          standard = Standard.where(:origin => origin, :position => row['ckOrder']).first_or_initialize
          standard.grade = grade
          standard.subject = row["Subject"]
          standard.ck_code = grade + "." + row["ckCode"].split(".", 2).last
          standard.ck_align = row["ckAlignCode"]
          standard.strand_code = row["StrandCode"]
          standard.strand = row["Strand/Domain"]
          standard.category = row["Category/Cluster"]
          standard.text = row["CCSS Standard"] || row["Standard"] || row["Standard Text"]
          standard.save
        end
      end
    end
  end

  def self.subjects_for_grade(grade)
    unscoped.common.for_grade(grade).select('distinct subject').map(&:subject)
  end

  def self.custom_subjects_for_grade(school, grade)
    unscoped.for_school(school).for_grade(grade).select('distinct subject').map(&:subject)
  end

end

app/controllers/admin/standards_controller.rb
class Admin::StandardsController < ApplicationController

  before_filter :require_admin

  def new_upload
  end

  def upload
    begin
      Standard.import(CSV.read(params[:file].tempfile, :headers => true))
      flash[:success] = "Standards imported successfully!"
    rescue Exception => e
      logger.error "Error importing standards: #{ e.inspect }"
      flash[:error] = "There was a problem importing your file. Please check the format and try again. The error: #{ e.inspect }"
    end
    redirect_to standards_path
  end

  def clear
    Standard.delete_all
    StandardApplication.delete_all
    flash[:notice] = "All standards have been destroyed!"
    redirect_to standards_path
  end

  def index
    @standards = standards.all.select(&:ck_code)
  end

  def show
    standard
  end

  def new
    @standard = standards.new(:position => max_common_position + 1)
  end
  
  def create
    @standard = standards.new(params[:standard])
    if @standard.save
      flash[:success] = "#{ standard.ck_code } has been created."
      redirect_to standards_path
    else
      flash.now[:error] = "There was a problem saving this standard."
      render :new
    end
  end

  def edit
    standard
  end

  def update
    if standard.update_attributes(params[:standard])
      flash[:success] = "Your changes to #{ standard.ck_code } have been saved."
      redirect_to standards_path
    else
      flash.now[:error] = "There was a problem saving your changes."
      render :edit
    end
  end

  def destroy
    standard.destroy
    flash[:success] = "#{ standard.ck_code } has been deleted."
    redirect_to standards_path
  end

  private

  def standard
    @standard ||= if params[:id]
                    standards.find(params[:id])
                  elsif params[:ck_code]
                    standards.where(:ck_code => params[:ck_code]).first
                  end
  end

  def standards
    @standards ||= Standard.common
  end

  def max_common_position
    @max_common_position ||= Standard.unscoped.common.select('max(position)').first['max'].to_i
  end

end

app/controllers/my_school/standards_controller.rb
class MySchool::StandardsController < ApplicationController

  before_filter :require_planner, :find_school

  def destroy
    @standard = @school.custom_standards.find(params[:id])
    if @standard.destroy
      respond_to do |format|
        format.html { redirect_to request.referer }
        format.json { render :json => { :success => :ok } }
      end
    end
  end

  def create
    @standard = @school.custom_standards.new(params[:standard])
    if @standard.save
      respond_to do |format|
        format.html { redirect_to request.referer }
        format.json { render :json => @standard }
      end
    else
      respond_to do |format|
        message =
          "Problem creating Standard: #{ @standard.errors.full_messages.join(', ') }"
        format.html { redirect_to request.referer,
                                  :flash => { :error => message }
        }
      end
    end
  end

  def update
    @standard = @school.custom_standards.find(params[:id])
    @standard.update_attributes(params[:standard])
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { render :json => @standard }
    end
  end

end

app/views/admin/standards/edit.html.haml
.row
  .span8.offset2
    = form_for @standard, :class => 'form form-horizontal' do |f|
      
      %fieldset
        %legend= "Edit #{ @standard.ck_code }"

        .controls
          = f.label :subject
          .control-group= f.select :subject, ["ELA/Literacy", "Math"]

        .controls
          = f.label :position, "CK Order"
          .control-group= f.number_field :position

        .controls
          = f.label :ck_code, "CK Code"
          .control-group= f.text_field :ck_code

        .controls
          = f.label :ck_align, "CK Align Code"
          .control-group= f.text_field :ck_align

        .controls
          = f.label :strand_code, "Strand Code"
          .control-group= f.text_field :strand_code
          
        .controls
          = f.label :strand, "Strand/Domain"
          .control-group= f.text_field :strand

        .controls
          = f.label :category
          .control-group= f.text_field :category

        .controls
          = f.label :text
          .control-group= f.text_area :text, :class => 'wysiwyg'

        .controls
          .control-group
            = f.submit "Save", :class => 'btn btn-primary'
            or
            = link_to "Cancel", standards_path

app/views/admin/standards/index.html.haml
.row
  .span12
    %h2 All Current Standards

    %p
      %strong Please note: This is the main database of the Core Knowledge online curriculum. Any changes you make here will affect all schools and all teachers.

    %p
      ELA/Literacy and Math standards are Copyright NGA Center and CCSSO and are used
      here by permission.

    %p= link_to "Add New Standard", new_standard_path

    %table.table.table-bordered
      %tr
        %th Subject
        %th CK Order
        %th CK Code
        %th CK Align Code
        %th Strand Code
        %th Strand/Domain
        %th Category/Cluster
        %th Standard
        %th
        %th

      - for standard in @standards
        %tr
          %td= standard.subject
          %td= standard.position
          %td= link_to standard.ck_code, standard_path(:ck_code => standard.ck_code, :format => :html)
          %td= standard.ck_align
          %td= standard.strand_code
          %td= standard.strand
          %td= standard.category
          %td= standard.text.html_safe
          %td
            = link_to "Edit", edit_standard_path(standard), :class => 'btn btn-primary'
          %td
            = button_to "Delete", standard_path(standard), :method => :delete, :class => 'btn btn-danger', :data => { :confirm => "Are you sure you want to delete this standard (#{ standard.ck_code })" }

app/views/admin/standards/new.html.haml
.row
  .span8.offset2
    = form_for @standard, :class => 'form form-horizontal' do |f|
      
      %fieldset
        %legend New Standard

        .controls
          = f.label :subject
          .control-group= f.select :subject, ["ELA/Literacy", "Math"]

        .controls
          = f.label :position, "CK Order"
          .control-group
            %p.help-block= "Note that a position less than #{ @max_common_position + 1 } will cause other standards ordered above that to be re-ordered."
            = f.number_field :position

        .controls
          = f.label :ck_code, "CK Code"
          .control-group= f.text_field :ck_code

        .controls
          = f.label :ck_align, "CK Align Code"
          .control-group= f.text_field :ck_align

        .controls
          = f.label :strand_code, "Strand Code"
          .control-group= f.text_field :strand_code
          
        .controls
          = f.label :strand, "Strand/Domain"
          .control-group= f.text_field :strand

        .controls
          = f.label :category
          .control-group= f.text_field :category

        .controls
          = f.label :text
          .control-group= f.text_area :text, :class => 'wysiwyg'

        .controls
          .control-group
            = f.submit "Save", :class => 'btn btn-primary'
            or
            = link_to "Cancel", standards_path

app/views/admin/standards/new_upload.html.haml
.row
  .span4
    = form_tag upload_standards_path, :class => 'form-vertical well', :multipart => true do
      %fieldset
        %legend Upload Standards
        .control-group
          = label_tag :file, "File to upload", :class => 'control-label'
          .controls= file_field_tag :file
          %p.help-block Choose a file in .csv format.

        .control-group
          .controls= submit_tag "Upload", :class => 'btn btn-primary'


    %fieldset
      %legend Clear All Standards

      %p
        Pressing this button will delete all standards. Proceed with caution!

      %p= button_to "Destroy Standards", clear_standards_path, :method => :delete, :class => 'btn btn-danger', :confirm => "Are you very, very sure?"

  .span8
    %h1 Instructions

    %p
      %strong Please note: This is the main database of the Core Knowledge online curriculum. Any changes you make here will affect all schools and all teachers.

    %p Your .csv file should have a structure like this, including the header row.

    %table.table.table-bordered
      %tr
        %th Subject
        %th ckOrder
        %th ckCode
        %th ckAlignCode
        %th StrandCode
        %th Strand/Domain
        %th Category/Cluster
        %th Standard Text
        %th Source

      %tr
        %td ELA/Literacy
        %td 1
        %td K.RL.1
        %td KRL.1
        %td RLK.1
        %td Reading Literature
        %td Key Ideas and Details
        %td With prompting and support, ask and answer questions about key details in a text.
        %td (optional; defaults to "CCSS")

app/views/admin/standards/show.html.haml
.row
  .span12
    
    %h2= "Standard #{ @standard.ck_code }"

    %table.table
      %tr
        %th Subject	
        %th CK Order
        %th CK Code
        %th CK Align Code
        %th Strand Code 
        %th Strand/Domain
        %th Category/Cluster
        %th Standard

      %tr
        %td= @standard.subject
        %td= @standard.position
        %td= @standard.ck_code
        %td= @standard.ck_align
        %td= @standard.strand_code
        %td= @standard.strand
        %td= @standard.category
        %td= @standard.text

    %p= link_to "Back to Standards", standards_path