config/routes.rb
DomainPlanner::Application.routes.draw do

  get '/sign_in' => 'user_sessions#new', :as => :sign_in
  post '/sign_in' => 'user_sessions#create', :as => :sign_in
  get '/sign_out' => 'user_sessions#destroy', :as => :sign_out

  get '/welcome-back' => 'welcome#welcome_back', :as => :user_landing

  scope 'about' do
    get 'core_knowledge' => 'about#core_knowledge', :as => :about_core_knowledge
    get 'terms_of_use' => 'about#terms_of_use', :as => :about_terms_of_use
    get 'software' => 'about#software', :as => :about_software
  end

  resources :password_resets, :except => [ :index, :destroy, :show ]

  get '/invitations/:role/new' => 'invitations#new', :as => :new_invitation
  post '/invitations/:role' => 'invitations#create', :as => :invitations
  get '/invitations/accept/:token' => 'invitations#show', :as => :accept_invitation
  put '/invitations/accept/:token' => 'invitations#accept', :as => :accept_invitation

  get '/school_invitations/new' => 'invitations#new_school', :as => :new_school_invitation
  post '/school_invitations' => 'invitations#create_school', :as => :school_invitations

  resources :users, :only => [ :index, :destroy ] do
    member do
      put :activate
      put :deactivate
      put :resend_invitation
    end
  end
  get 'users/all.csv' => 'users#csv'

  get '/me', :to => 'users#edit'
  put '/me', :to => 'users#update'

  get '/my_school/edit' => 'my_school#edit', :as => :edit_my_school
  put '/my_school' => 'my_school#update', :as => :my_school

  scope 'my_school' do
    resources :scheduled_domains
    resources :school_holidays
    resources :school_years, :controller => 'my_school/school_years'

    get 'school_years/:id/transfer' => 'my_school/school_years#transfer', :as => :transfer_school_year
    put 'school_years/:id/transfer' => 'my_school/school_years#complete_transfer'

    get 'school_years/:id/schedule' => 'my_school/school_years#schedule', :as => :school_year_schedule
    put 'school_years/:id/schedule' => 'my_school/school_years#update_schedule'

    resources :domains, :controller => 'my_school/domains', :as => :custom_domains, :only => [:create, :destroy, :update]
    resources :standards, :controller => 'my_school/standards', :as => :custom_standards, :only => [ :create, :destroy, :update ]
    resources :guidelines, :controller => 'my_school/guidelines', :as => :custom_guidelines, :only => [ :create, :destroy, :update ]

    scope '/users' do
      get '/', :to => 'my_school/users#index', :as => :my_school_users
      put '/:id/activate', :to => 'my_school/users#activate', :as => :activate_user
      put '/:id/deactivate', :to => 'my_school/users#deactivate', :as => :deactivate_user
      put '/:id/promote', :to => 'my_school/users#promote', :as => :promote_user
      put '/:id/demote', :to => 'my_school/users#demote', :as => :demote_user
    end

    scope '/domain_maps/:domain_id/school_years/:school_year_id' do
      get '/', :to => 'my_school/domain_maps#show', :as => :domain_map
      post '/guidelines/:guideline_id', :to => 'my_school/mapped_guidelines#create', :as => :mapped_guidelines
      delete '/guidelines/:guideline_id', :to => 'my_school/mapped_guidelines#destroy', :as => :mapped_guidelines
      post '/skills_guidelines/:guideline_id', :to => 'my_school/mapped_skills_guidelines#create', :as => :mapped_skills_guidelines
      delete '/skills_guidelines/:guideline_id', :to => 'my_school/mapped_skills_guidelines#destroy', :as => :mapped_skills_guidelines

      put '/included_standards/:id', :to => 'my_school/domain_maps#include_standard', :as => 'include_standard'
      delete '/included_standards/:id', :to => 'my_school/domain_maps#omit_standard', :as => 'omit_standard'
      get '/included_standards', :to => 'my_school/domain_maps#included_standards', :as => 'included_standards'
      put '/included_skills_standards/:id', :to => 'my_school/domain_maps#include_skills_standard', :as => 'include_skills_standard'
      delete '/included_skills_standards/:id', :to => 'my_school/domain_maps#omit_skills_standard', :as => 'omit_skills_standard'
      get '/included_skills_standards', :to => 'my_school/domain_maps#included_skills_standards', :as => 'included_skills_standards'

      put '/toggle_cross_curricular_link/:id', :to => 'my_school/domain_maps#toggle_cross_curricular_link', :as => 'toggle_cross_curricular_link'

      put '/vocabulary', :to => 'my_school/domain_maps#add_vocabulary', :as => 'domain_map_vocabulary'
      delete '/vocabulary/:word', :to => 'my_school/domain_maps#remove_vocabulary', :as => 'domain_map_vocabulary_word'
    end

    get '/teachers/invitations/new', :to => 'my_school/teacher_invitations#new', :as => :new_teacher_invitation
    post '/teachers/invitations', :to => 'my_school/teacher_invitations#create', :as => :teacher_invitations

    get '/planners/invitations/new', :to => 'my_school/planner_invitations#new', :as => :new_my_school_planner_invitation
    post '/planners/invitations', :to => 'my_school/planner_invitations#create', :as => :my_school_planner_invitations


  end

  get '/domains' => 'domains#grades', :as => :domains
  get '/domains/new' => 'domains#new', :as => :new_domain
  post '/domains' => 'domains#create', :as => :domains
  get '/domains/:grade' => 'domains#grade', :as => :domains_grade
  get '/domains/:grade/:id' => 'domains#show', :as => :domain

  scope '/admin' do

    scope '/curriculum' do
      get '/' => 'curriculum#index', :as => :curriculum
      get '/upload' => 'curriculum#new', :as => :upload_curriculum
      post '/' => 'curriculum#upload', :as => :curriculum
      delete '/' => 'curriculum#clear', :as => :clear_curriculum
      get '/curriculum/node/:id' => 'curriculum#node', :as => :curriculum_node

      get 'node/:id/children/new' => 'admin/curriculum_nodes#new', :as => :new_child_curriculum_node
      get 'node/new' => 'admin/curriculum_nodes#new', :as => :new_curriculum_node
      post 'nodes' => 'admin/curriculum_nodes#create', :as => :curriculum_nodes
      get 'node/:curriculum_node_id/guidelines/new' => 'admin/guidelines#new', :as => :new_guideline
      post 'node/:curriculum_node_id/guidelines' => 'admin/guidelines#create', :as => :guidelines

      get '/curriculum/node/:id/edit' => 'curriculum#edit', :as => :edit_curriculum_node
      put '/curriculum/node/:id' => 'curriculum#update', :as => :curriculum_node
      delete '/curriculum/node/:id' => 'curriculum#destroy', :as => :curriculum_node
    end

    scope '/domains' do
      get '/' => 'admin/domains#new', :as => :upload_domains
      post '/' => 'admin/domains#upload', :as => :upload_domains
      delete '/' => 'admin/domains#clear', :as => :clear_domains
      put '/:id' => 'admin/domains#update', :as => :admin_domain
      delete '/:id' => 'admin/domains#destroy', :as => :admin_domain
    end

    resources :guidelines, :only => [ :show, :edit, :update, :destroy], :controller => 'admin/guidelines' do
      resources :knowledge_connections, :only => [ :create, :destroy ], :controller => 'admin/knowledge_connections'
      resources :domain_applications, :only => [ :create, :destroy ], :controller => 'admin/guideline_domain_applications'
      resources :standard_applications, :only => [ :create, :destroy ], :controller => 'admin/guideline_standard_applications'
      resources :sub_guidelines, :only => [ :create ], :controller => 'admin/sub_guidelines'
    end
    resources :sub_guidelines, :only => [ :edit, :update, :destroy ], :controller => 'admin/sub_guidelines'

    resources :standards, :controller => 'admin/standards'

    get '/upload/standards' => 'admin/standards#new_upload', :as => :new_standards_upload
    get '/standards/*ck_code' => 'admin/standards#show', :as => :standard
    post '/upload/standards' => 'admin/standards#upload', :as => :upload_standards
    delete '/standards' => 'admin/standards#clear', :as => :clear_standards

    get 'logins' => 'admin/login_events#index', :as => :login_events
    get 'schools' => 'admin/schools#index', :as => :admin_schools
    get 'lesson_plans' => 'admin/lesson_plans#index', :as => :admin_lesson_plans
  end

  get 'schools' => 'schools#index', :as => :schools

  get '/curriculum/plan/:grade' => 'my_school#plan', :as => :plan_curriculum
  get '/curriculum/plan/:grade/domains' => 'my_school#domains'
  get '/curriculum/plan/:grade/scheduled_domains' => 'my_school#scheduled_domains'

  get '/my_school/curriculum/(:grade)' => 'teachers/domain_maps#curriculum', :as => :show_curriculum
  get '/my_school/curriculum/school_years/:school_year_id/domain_map/:domain_id' => 'teachers/domain_maps#domain_map', :as => :show_domain_map

  get '/my_calendar' => 'teachers/calendar#show', :as => :teacher_calendar
  get '/my_calendar/events' => 'teachers/calendar#events', :as => :teacher_calendar_events
  post '/my_calendar/:school_year_id/:month_fragment' => 'teachers/calendar#persist_month'

  post '/school_years/:school_year_id/scheduled_lesson_plans' => 'teachers/scheduled_lesson_plans#create', :as => :scheduled_lesson_plans

  get '/guidelines/:guideline_id/knowledge_connections' => 'knowledge_connections#index', :as => :knowledge_connections

  scope '/domains/:domain_id' do
    resources :domain_units, :only => [ :create, :update, :destroy ], :controller => 'schools/domain_units' do
      resources :lesson_plans, :controller => 'teachers/lesson_plans' do
        member { put :clone; put :public_notes }
      end
    end
  end

  resources :lesson_plans, :only => [ :show ], :controller => 'teachers/lesson_plans'

  scope '/reports' do

    # Reports

    get '/', :to => 'reports#index', :as => :reports

    [ :grade_domain_report, :subject_domain_report, :ccss_coverage_report, :domain_week_report, :ss_coverage_report, :full_domain_report, :domain_lessons_report, :related_knowledge_report ].each do |report|
      get "#{ report }/new", :to => "reports/#{ report.to_s.pluralize }#new", :as => "new_#{ report }"

app/models/guideline.rb
class Guideline < ActiveRecord::Base

  belongs_to :curriculum_node

  has_many :domain_applications, :as => :applicable, :dependent => :destroy
  has_many :domains, :through => :domain_applications

  has_many :standard_applications, :dependent => :destroy
  has_many :standards, :through => :standard_applications

  has_many :sub_guidelines

  has_many :knowledge_connections

  has_many :prior_knowledge_curriculum_nodes, :through => :knowledge_connections, :source => :prior_knowledge, :source_type => 'CurriculumNode'
  has_many :future_knowledge_curriculum_nodes, :through => :knowledge_connections, :source => :future_knowledge, :source_type => 'CurriculumNode'
  has_many :cross_knowledge_curriculum_nodes, :through => :knowledge_connections, :source => :cross_knowledge, :source_type => 'CurriculumNode'
  has_many :prior_knowledge_guidelines, :through => :knowledge_connections, :source => :prior_knowledge, :source_type => 'Guideline'
  has_many :future_knowledge_guidelines, :through => :knowledge_connections, :source => :future_knowledge, :source_type => 'Guideline'
  has_many :cross_knowledge_guidelines, :through => :knowledge_connections, :source => :cross_knowledge, :source_type => 'Guideline'

  attr_accessible :name, :notes, :school_id, :curriculum_node_id

  scope :common, lambda { where(:school_id => nil) }
  scope :for_school, lambda { |school|
    where(:school_id => [nil, school.id])
  }

  def prior_knowledge_connections
    prior_knowledge_guidelines + prior_knowledge_curriculum_nodes
  end

  def cross_knowledge_connections
    cross_knowledge_guidelines + cross_knowledge_curriculum_nodes
  end

  def future_knowledge_connections
    future_knowledge_guidelines + future_knowledge_curriculum_nodes
  end
  
  def position
    id
  end

  def abbreviated_text
    name.size > 30 ? "#{ name[0..27] }..." : name
  end

  def inherited_domains
    (curriculum_node.inherited_domains + domains).flatten.uniq
  end

  def name_with_prefix
    name
  end

  def grade_name
    curriculum_node.grade_name
  end

  def grade
    curriculum_node.grade
  end

  def custom?
    school_id.present?
  end

end

app/controllers/admin/guidelines_controller.rb
class Admin::GuidelinesController < InheritedResources::Base

  before_filter :require_admin

  def show
    @subjects = CurriculumNode.roots.all
    show!
  end

  def new
    @guideline = curriculum_node.guidelines.new
  end

  def create
    @guideline = curriculum_node.guidelines.new(params[:guideline])
    if @guideline.save
      redirect_to guideline_path(@guideline)
    else
      flash.now[:error] = "There was a problem creating this guideline."
      render :new
    end
  end

  def update
    update! { guideline_path(@guideline) }
  end

  def destroy
    destroy! { curriculum_node_path(@guideline.curriculum_node) }
  end

  private

  def resource
    @guideline ||= Guideline.includes(:knowledge_connections, :domain_applications, :standard_applications, :sub_guidelines).find(params[:id])
  end

  def curriculum_node
    @curriculum_node ||= CurriculumNode.find(params[:curriculum_node_id])
  end

end

app/controllers/my_school/guidelines_controller.rb
class MySchool::GuidelinesController < ApplicationController

  before_filter :require_planner, :find_school

  def destroy
    @guideline = @school.custom_guidelines.find(params[:id])
    if @guideline.destroy
      respond_to do |format|
        format.html { redirect_to request.referer }
        format.json { render :json => { :success => :ok } }
      end
    end
  end

  def create
    @guideline = @school.custom_guidelines.create(params[:guideline])
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { render :json => @guideline }
    end
  end

  def update
    @guideline = @school.custom_guidelines.find(params[:id])
    @guideline.update_attributes(params[:guideline])
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { render :json => @guideline }
    end
  end

end

app/controllers/public_curriculum/guidelines_controller.rb
class PublicCurriculum::GuidelinesController < ApplicationController

  def show
    @guideline = Guideline.includes(:sub_guidelines).find(params[:id])
  end

end

app/helpers/admin/guidelines_helper.rb
module Admin::GuidelinesHelper
end

app/views/admin/guidelines/_curriculum_node.html.haml
%li.hide
  %i.icon-folder-close
  = link_to curriculum_node.name, '#', :class => 'curriculum-node knowledge-connection', :data => { 'knowledge-id' => curriculum_node.id, 'knowledge-type' => 'CurriculumNode' }
  %ul.unstyled{:class => "indent#{ (curriculum_node.depth + 1) * 5 }"}
    = render :partial => 'curriculum_node', :collection => curriculum_node.children.order('position asc')
    = render :partial => 'guideline', :collection => curriculum_node.guidelines.common

app/views/admin/guidelines/_guideline.html.haml
%li.hide
  %i.icon-bookmark
  = link_to guideline.name.html_safe, '#', :class => 'knowledge-connection', :data => { 'knowledge-id' => guideline.id, 'knowledge-type' => 'Guideline' }

app/views/admin/guidelines/_sub_guideline.html.haml
%tr
  %td= sub_guideline.name
  %td
    = link_to "Edit", edit_sub_guideline_path(sub_guideline), :class => 'btn'
    = link_to "Delete", sub_guideline_path(sub_guideline), :class => 'btn btn-danger', :method => :delete
  

app/views/admin/guidelines/edit.html.haml
.row
  .span8
    = form_for @guideline, :class => 'form' do |f|

      %fieldset
        %legend= "Edit #{ @guideline.abbreviated_text }"

        .controls
          = f.label :name
          .control-group= f.text_area :name, :class => 'wysiwyg'

        .controls
          = f.label :notes
          .control-group= f.text_area :notes, :class => 'wysiwyg'

        .controls
          .control-group
            = f.submit "Save", :class => 'btn btn-primary'
            = link_to "Cancel", @guideline, :class => 'btn btn-cancel'


    %p= button_to "Delete", @guideline, :method => :delete, :class => 'btn btn-danger', :data => { :confirm => "Are you sure you want to delete this guideline? All associated data will also be deleted." }

app/views/admin/guidelines/new.html.haml
.row
  .span8
    = form_for @guideline, :path => guidelines_path(:curriculum_node_id => @curriculum_node.id), :class => 'form' do |f|

      %fieldset
        %legend New Guideline

        .controls
          = f.label :name
          .control-group= f.text_area :name, :class => 'wysiwyg'

        .controls
          = f.label :notes
          .control-group= f.text_area :notes, :class => 'wysiwyg'

        .controls
          .control-group
            = f.submit "Save", :class => 'btn btn-primary'
            = link_to "Cancel", curriculum_node_path(@curriculum_node), :class => 'btn btn-cancel'

app/views/admin/guidelines/show.html.haml
.row
  .span12
    %ul.breadcrumb
      - for ancestor in @guideline.curriculum_node.ancestors.all.sort_by(&:depth)
        %li= link_to ancestor.name, curriculum_node_path(ancestor)
        = "/"
      %li= link_to @guideline.curriculum_node.name, curriculum_node_path(@guideline.curriculum_node)
      = "|"
      %li
        = @guideline.abbreviated_text.html_safe
        %a{:href => edit_guideline_path(@guideline)}
          %i.icon-pencil
.row
  .span3.well
    %h3 Curriculum Browser
    %ul.curriculum.curriculum-source.unstyled.tree-browser
      - for subject in @subjects
        %li{:class => ('ela' if subject.name == 'Language Arts')}
          %i.icon-folder-close
          = link_to subject.name, "#", :class => 'curriculum-node'
          %ul.unstyled.indent5= render :partial => 'curriculum_node', :collection => subject.children.order('position asc')

  .span8
    
    %h4= @guideline.name.inspect.html_safe

    %h3
      Knowledge Connections

    %table.table.table-bordered
      %tr
        %th Prior Knowledge
        %th Future Knowledge
        %th Cross Curricular Links

      %tr
        %td.knowledge-connections#prior-knowledge
          %ul
        %td.knowledge-connections#future-knowledge
          %ul
        %td.knowledge-connections#cross-curricular
          %ul

    %h3
      Domains
      
    %table.table.table-bordered
      %tr
        %th Available Domains
        %th Associated Domains
      %tr
        %td
          %ul
            - for domain in Domain.common.for_grade(@guideline.grade)
              %li.domain{:data => { :domain_id => domain.id }}= domain.name
        %td#domain-applications
          %ul

    %h3
      Standards
    
    %table.table.table-bordered
      %tr
        %th Available Standards
        %th Associated Standards
      %tr
        %td

          %ul.curriculum.standards-browser.unstyled.tree-browser
            - for subject in Standard.subjects_for_grade(@guideline.grade)
              %li
                %i.icon-folder-close
                = link_to subject, '#', :class => 'standard-subject'
                %ul.indent5.unstyled
                  = render :partial => 'my_school/domain_maps/standard', :collection => Standard.common.for_grade(@guideline.grade).for_subject(subject)
        %td#standard-applications
          %ul

    %h3 Sub-Guidelines
    
    %table.table.tabel-bordered
      %tr
        %th Text
        %th Actions
      = render :partial => 'sub_guideline', :collection => @guideline.sub_guidelines
      = form_for SubGuideline.new, :url => guideline_sub_guidelines_path(@guideline) do |f|
        %tr
          %td= f.text_field :name, :placeholder => "Text"
          %td= f.submit "Add New", :class => 'btn btn-primary'

.row
  .span3.offset9
    %p= link_to "<< #{ @guideline.curriculum_node.name }", @guideline.curriculum_node

= content_for :extra_head do
  = javascript_tag "window.guidelineId = #{ @guideline.id };"
  = javascript_tag "window.initialKnowledgeConnections = #{ @guideline.knowledge_connections.to_json };"
  = javascript_tag "window.initialDomainApplications = #{ @guideline.domain_applications.to_json(:methods => [ :id, :domain_name ]) };"
  = javascript_tag "window.initialStandardApplications = #{ @guideline.standard_applications.to_json(:methods => [ :id, :standard_text, :standard_short_text, :standard_ck_code, :standard_id ]) };"